require 'rake'
require 'rspec/core/rake_task'
require_relative 'db/config'
require_relative 'lib/UsersImporter'


desc "create the database"
task "db:create" do
  touch 'db/split-mvp.sqlite3'
end

desc "drop the database"
task "db:drop" do
  rm_f 'db/split-mvp.sqlite3'
end

desc "migrate the database (options: VERSION=x, VERBOSE=false, SCOPE=blog)."
task "db:migrate" do
  ActiveRecord::Migrator.migrations_paths << File.dirname(__FILE__) + 'db/migrate'
  ActiveRecord::Migration.verbose = ENV["VERBOSE"] ? ENV["VERBOSE"] == "true" : true
  ActiveRecord::Migrator.migrate(ActiveRecord::Migrator.migrations_paths, ENV["VERSION"] ? ENV["VERSION"].to_i : nil) do |migration|
    ENV["SCOPE"].blank? || (ENV["SCOPE"] == migration.scope)
  end
end

desc "populate the test database with sample data"
task "db:populate" do
  UsersImporter.import
end


desc "rollback your migration--use STEPS=number to step back multiple times"
task "db:rollback" do
  steps = (ENV['STEPS'] || 1).to_i
  ActiveRecord::Migrator.rollback('db/migrate', steps)
  Rake::Task['db:version'].invoke if Rake::Task['db:version']
end

desc 'Retrieves the current schema version number'
task "db:version" do
  puts "Current version: #{ActiveRecord::Migrator.current_version}"
end

desc 'opens up the model files in the console'
task "db:console" do
  exec "irb -r ./db/config.rb"
end

desc 'opens up the current working SQlite3 database'
task "db" do
  exec "sqlite3 ./db/split-mvp.sqlite3"
end

desc "Run the specs"
RSpec::Core::RakeTask.new(:specs)

task :default  => :specs
